name: AI Code Reviewer

on:
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  pull_request_target:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: tmi-quanha/llm-code-review@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          GOOGLE_GENERATIVE_AI_MODEL: ${{ secrets.GOOGLE_GENERATIVE_AI_MODEL }}
          OPENAI_API_MODEL: ${{ secrets.OPENAI_API_MODEL }}
          AI_VENDOR: ${{ secrets.AI_VENDOR }} # google or openai
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas